apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: neo4j
  ports:
  - port: 7474
    name: browser
    targetPort: 7474
    protocol: TCP
  - port: 7687
    name: bolt
    targetPort: 7687
    protocol: TCP
  type: LoadBalancer 