neo4j:
  name: "neo4j-release"
  edition: "community"
  namespace: "neo4j-system"
  
  # 使用 Secret 作为密码来源
  passwordFromSecret: "neo4j-auth-secret"

  # 资源配置
  resources:
    requests:
      cpu: "4"
      memory: "16Gi"
    limits:
      cpu: "6"
      memory: "24Gi"

# 存储配置
volumes:
  data:
    mode: "dynamic"
    dynamic:
      storageClassName: "default"
      accessModes: ["ReadWriteOnce"]
      requests:
        storage: "200Gi"
  logs:
    mode: "dynamic"
    dynamic:
      storageClassName: "default"
      accessModes: ["ReadWriteOnce"]
      requests:
        storage: "20Gi"
  backups:
    mode: "share"
    share:
      name: "data"

# 服务配置
services:
  neo4j:
    enabled: true
    annotations: {}
    spec:
      type: LoadBalancer
      ports:
        http:
          port: 7474
          enabled: true
        https:
          port: 7473
          enabled: false
        bolt:
          port: 7687
          enabled: true

# 集群配置
config:
  dbms.mode: CORE
  dbms.clustering.discovery.type: DNS 