neo4j:
  name: "my-neo4j"
  edition: "community"
  password: "your-secure-password"

# 资源配置
resources:
  cpu: "1"
  memory: "4Gi"

# 存储配置  
volumes:
  data:
    mode: "defaultStorageClass"
    size: "10Gi"

# 服务配置
services:
  neo4j:
    enabled: true
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    spec:
      type: LoadBalancer
      loadBalancerIP: ""
    ports:
      http:
        enabled: true
      https:
        enabled: false  
      bolt:
        enabled: true

# 集群配置
config:
  dbms.mode: CORE
  dbms.clustering.discovery.type: DNS 