neo4j:
  name: "neo4j-release"
  edition: "community"
  namespace: "neo4j-system"
  
  # 使用 Secret 作为密码来源
  passwordFromSecret: "neo4j-auth-secret"

# 资源配置
resources:
  cpu: "1"
  memory: "4Gi"

# 存储配置  
volumes:
  data:
    mode: "defaultStorageClass"
    size: "10Gi"

# 服务配置
services:
  neo4j:
    enabled: true
    annotations: {}
    spec:
      type: LoadBalancer
      ports:
        http:
          port: 7474
          enabled: true
        https:
          port: 7473
          enabled: false
        bolt:
          port: 7687
          enabled: true

# 集群配置
config:
  dbms.mode: CORE
  dbms.clustering.discovery.type: DNS 